# Zyra FT left peripheral

# Disable display
CONFIG_ZMK_DISPLAY=n

# Enable BLE and USB
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Deep sleep support
CONFIG_ZMK_SLEEP=y

# 15 minut idle timeout
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Eager debouncing - mniej lagu
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Mouse keys
CONFIG_ZMK_POINTING=y

# BLE passkey - bezpieczne pairing
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y
