# Zyra FT right peripheral

# Deep sleep support
CONFIG_ZMK_SLEEP=y

# 15 minut idle timeout
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Mouse keys
CONFIG_ZMK_POINTING=y

# Disable display
CONFIG_ZMK_DISPLAY=n
